Added parameters to set the height and width of the flag and changed help shorthand to "?"
ExperiBass/cli-pride-flags pull request #19
Opened 2024-05-22 18:32 UTC by miel8

Added width and height parameters that override the values normally gotten with "process.stdout.rows" and "process.stdout.columns" to allow setting the dimensions of the flag.
Due to the base scaling not being 100% reliable, sometimes a different height then specified is generated, but it's good enough to get a desired height.
Also, if a width is specified, a newline character is added to the end of all lines so the flag is displayed correctly

Also changed the help shorthand from "h" to "?" to allow height to have the shorthand "h". This short doesn't work in all shells, however it works in bash and the help is also accessible with --help or not passing in any arguments so I don't think this is an issue.

2024-05-22 20:01 UTC, ExperiBass requested changes

2024-05-22 20:01 UTC, 0xf0xx0 commented on src/main.js
> +            finishedFlag += '\n'
this leaves a dangling newline, you can slap on a `.trim()` after `.repeat(availableHeight)` to fix

2024-05-22 20:01 UTC, 0xf0xx0 commented on src/main.js
> +        finishedFlag += chalk.hex(color)(CHAR.repeat(availableWidth)) + (options.width ? '\n' : '')
dangling newline here as well

2024-05-22 20:01 UTC, 0xf0xx0 commented on src/main.js
> +        const availableHeight = options.height ? options.height : process.stdout.rows
these should check if the passed number is greater than 0, we cant inverse `.repeat` x3

2024-05-22 20:01 UTC, 0xf0xx0 commented on src/main.js
> +    help: { type: 'boolean', short: '?', description: 'Display this help text' },
thisll be fine tbh, at least in `zsh` it becomes `-\?`  
if it ends up being a issue i can always drop one of the aliases

2024-05-22 20:21 UTC, miel8 commented
i added a check after the definition of availableHeight and availableWidth that throws "Width and height must be greater than 0" if either isn't. is that good or should i change the error message / just take the shell dimensions

2024-05-23 14:37 UTC, ExperiBass commented
Throwing an error is fine, if you can wrap it up in a `new Error()` and run it through [Prettier](https://prettier.io/) i'll merge :3

2024-05-23 19:54 UTC, ExperiBass approved these changes

2024-05-23 20:00 UTC, merged